spring:
  jpa:
    show-sql: true
    properties:
      hibernate.hibernate.default_schema: public
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/vetmed
  application:
    name: web-application
  liquibase:
    change-log: classpath:db/changelog/main-changelog.xml
logging:
  level:
    org.springframework.security: DEBUG
    web: DEBUG
